/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2018-12-20 06:09:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;

public final class joinEL_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		Cookie cook = new Cookie("cook", "cook!");
		response.addCookie(cook);
		
		session.setAttribute("ses", "session!");
		
		application.setAttribute("app", "application!");
	
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("\t<font face=\"나눔고딕\" size=\"8\">Sign Up</font><br>\r\n");
      out.write("\tfor Our Blogging System Today!<br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"onlyEL.jsp\" method=\"post\">\r\n");
      out.write("\t<table width=\"600\" align=\"center\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" bgcolor=\"cornflowerBlue\"><h3>&nbspStep 1 : Account Information</h3></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr bgcolor=\"whitesmoke\" height=\"40\">\r\n");
      out.write("\t\t\t<td align=\"right\">Your Name&nbsp</center></td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" size=\"40\" placeholder=\"이름을 입력하세요\" name=\"name\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr bgcolor=\"whitesmoke\" height=\"40\">\r\n");
      out.write("\t\t\t<td align=\"right\">Email&nbsp</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" size=\"40\" name=\"email\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr bgcolor=\"whitesmoke\" height=\"40\">\r\n");
      out.write("\t\t\t<td align=\"right\">Password&nbsp</td>\r\n");
      out.write("\t\t\t<td><input type=\"password\" size=\"40\" name=\"password\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" bgcolor=\"cornflowerBlue\"><h3>&nbspStep 2 : Billing Details</h3></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr bgcolor=\"whitesmoke\" height=\"40\">\r\n");
      out.write("\t\t\t<td align=\"right\">Gender&nbsp</td>\r\n");
      out.write("\t\t\t<td>Man<input type=\"radio\" size=\"40\" name=\"gender\" checked=\"checked\" value=\"man\">Women<input type=\"radio\" size=\"40\" name=\"gender\" value=\"women\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr bgcolor=\"whitesmoke\" height=\"40\">\r\n");
      out.write("\t\t\t<td align=\"right\">Phone&nbsp</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" size=\"40\" name=\"phone\"><br>\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"sendcheck\">Yes, text me Update and opecial announcements</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr bgcolor=\"whitesmoke\" height=\"40\">\r\n");
      out.write("\t\t\t<td align=\"right\">Country&nbsp</td>\r\n");
      out.write("\t\t\t<td><select name=\"country\">\r\n");
      out.write("\t\t\t\t<option>Choice..</option>\r\n");
      out.write("\t\t\t\t<option>South Korea</option>\r\n");
      out.write("\t\t\t\t<option>U.S.A</option>\r\n");
      out.write("\t\t\t</select></td>\r\n");
      out.write("\t\t</tr>\t\r\n");
      out.write("\t\t<tr bgcolor=\"whitesmoke\" height=\"40\">\r\n");
      out.write("\t\t\t<td align=\"right\">Address&nbsp</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" size=\"40\" name=\"address\">&nbsp<input type=\"button\" value=\"find address\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr bgcolor=\"whitesmoke\" height=\"40\">\r\n");
      out.write("\t\t\t<td align=\"right\">Your Birthday&nbsp</td>\r\n");
      out.write("\t\t\t<td><input type=\"date\" name=\"birth\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" bgcolor=\"cornflowerBlue\"><h3>&nbspStep 3 : Your favorite</h3></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr bgcolor=\"whitesmoke\" height=\"40\">\r\n");
      out.write("\t\t\t<td align=\"right\">Choice Your Hobby&nbsp</td>\r\n");
      out.write("\t\t\t<td>sport<input type=\"checkbox\" name=\"hobby\" value=\"운동\">study<input type=\"checkbox\" name=\"hobby\" value=\"공부\">reading<input type=\"checkbox\" name=\"hobby\">meeting<input type=\"checkbox\" name=\"hobby\">eating<input type=\"checkbox\" name=\"hobby\"><br>\r\n");
      out.write("\t\t\texcept..<input type=\"text\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr bgcolor=\"whitesmoke\" height=\"40\">\r\n");
      out.write("\t\t\t<td align=\"right\">Favorite Color&nbsp</td>\r\n");
      out.write("\t\t\t<td><input type=\"color\" name=\"color\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" bgcolor=\"cornflowerBlue\"><h3>&nbspStep 4 : Talk us!</h3></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr bgcolor=\"whitesmoke\" height=\"40\">\r\n");
      out.write("\t\t\t<td colspan=\"2\"><textarea rows=\"20\" cols=\"90\" name=\"talk\"></textarea></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr align=\"center\" bgcolor=\"whitesmoke\">\r\n");
      out.write("\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Join\"><input type=\"reset\" value=\"Return\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("</center>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
